services:
    laravel.test:
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:5173'
    mysql:
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
    # redis:
    #     ports:
    #         - '${FORWARD_REDIS_PORT:-6379}:6379'
    # minio:
    #     ports:
    #         - '${FORWARD_MINIO_PORT:-9000}:9000'
    #         - '${FORWARD_MINIO_CONSOLE_PORT:-8900}:8900'
